# Generated by Django 5.0.3 on 2024-03-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userprofile_slogan_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.CharField(default='Dublin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='continent',
            field=models.CharField(choices=[('NA', 'North America'), ('SA', 'South America'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('OC', 'Oceania'), ('AN', 'Antarctica')], default='EU', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(default='Ireland', max_length=255),
            preserve_default=False,
        ),
    ]
