# Generated by Django 5.0.3 on 2024-04-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userprofile_prefered_destination_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='prefered_destination_type',
        ),
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PreferedDestinationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefered_destination_type', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='app.userprofile')),
            ],
        ),
    ]
