# Generated by Django 5.0.3 on 2024-04-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_destinationrating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prefereddestinationtype',
            unique_together={('user', 'prefered_destination_type')},
        ),
    ]
